### ISSUE TITLE
3D Touch Quick Actions from Home Screen Icon

### ISSUE THREAD

**Issue by mattbarker016** [cuappdev/ithaca-transit-ios#106]
We could show favorites, or recents, or let users customize what appears!

**Comment by myo3** [comment]
**Update on specification from meeting (9/12):**
Show the all the favorites on the 3D Touch Quick Action menu. Get rid of the Share option on the menu. 

According to Apple Docs, you can have up to 4, but Brella has 5 so see if can show all 5 favorites and if not show the first 4 favorites.
