### ISSUE TITLE
Updating Route Options Routes Screen

### ISSUE THREAD

**Issue by mattbarker016** [cuappdev/ithaca-transit-ios#108]
If you re-open the app or come back to Route Options after a while, routes for an older time are shown, which looks confusing because the routes are implied to be live. Maybe after 5 minutes update the Route Options page with fresh routes and an updates Leave Now time?

**Comment by mattbarker016** [comment]
@myo3 Has this been taken care of? Also, Mihir showed me an odd bug where the cell will flicker between on time and late, but it's the same time. 

**8:50 - 9:07**
On Time

... 5 seconds later ...

**8:50 - 9:07**
Late - 8:50 PM

**Comment by myo3** [comment]
I thought we agreed that pull to refresh would update routes. B/c I don't think Google maps refreshes the page if you come back to it. 

And okay I'll make note of it. Did/can Mihir submit it to the bug form? Just need the date & time, the start & end location so I can recreate the bug and figure it out

**Comment by mattbarker016** [comment]
Yeah, it's clearer now because you show the time being used for leave now
