### ISSUE TITLE
Use SnapKit for layout

### ISSUE THREAD

**Issue by mattbarker016** [cuappdev/ithaca-transit-ios#130]
SnapKit is pretty darn good, especially at readability. If there's time in this refactor period, this would be good to use throughout the app!

### Cells:
- [x] BusStopTableViewCell
- [x] GeneralTableViewCell
- [x] LargeDetailTableViewCell
- [x] RouteTableViewCell
- [x] ServiceAlertTableViewCell
- [x] PlaceTableViewCell
- [x] SmallDetailTableViewCell

### Controllers:
- [x] AllStopsTableViewController
- [x] CustomNavigationController
- [x] FavoritesTableViewController
- [x] HomeMapViewController
- [x] HomeOptionsCardViewController
- [x] InformationViewController
- [x] OnboardingViewController
- [x] RouteDetailViewController 
- [x] RouteDetail+ContentViewController
- [x] RouteDetail+DrawerViewController
- [x] RouteDetailDrawerViewController+Extensions
- [x] RouteOptionsViewController
- [x] RouteOptionsViewController+Extensions
- [x] SearchResultsTableViewController
- [x] ServiceAlertsViewController

### Views:
- [x] BusIcon
- [x] BusLocationView (PR: #264)
- [x] Circle
- [x] DatePickerView
- [x] DetailIconView
- [x] HeaderView
- [x] LiveIndicator (PR: #263)
- [x] LoadingIndicator
- [x] PhraseLabelFooterView
- [x] RoundedShadowedView
- [x] RouteDiagram
- [x] RouteDiagramSegment
- [x] RouteLine
- [x] RouteSelectionView
- [x] SearchBarView
- [x] SummaryView
- [x] WalkWithDistanceIcon
- [x] WhatsNewHeaderVie
- [x] InformationTableHeaderView

**Comment by Omarrasheed** [comment]
Closing because I tackled this in snapkit PR. The last VC (RouteDetail+ContentVC) still needs some frame-based layout because it interacts directly with google's api to place markers on the map.
