### ISSUE TITLE
Fix RouteDetailViewController ending destination

### ISSUE THREAD

**Issue by AAAstorga** [cuappdev/ithaca-transit-ios#131]
When selecting a route and ending up on the RouteDetailViewController, the final destination always says 'Walk to Current Location'. 

Needs to be fixed ASAP.

![img_2752](https://user-images.githubusercontent.com/15990084/44633593-81d2e400-a95b-11e8-8422-2301324c58b3.PNG)

**Comment by mattbarker016** [comment]
Resolved, thanks for the catch! Would love to refactor the 🍝 of `Route.swift` @myo3
