### ISSUE TITLE
Can we cut down on any pods?

### ISSUE THREAD

**Issue by AAAstorga** [cuappdev/ithaca-transit-ios#135]
I'm looking at the pods and we have a lot. Anyway we can cut down to reduce final size of app? The smaller the better

**Comment by mattbarker016** [comment]
Removing Register helped cut down on a lot of cruft. We could potentially replaced TRON and SwiftyJSON with Moya and Coable support. Those already exist in other issues. I'm going to close this, since we've partially done this, and I don't see anything else we can remove at the moment.
