### ISSUE TITLE
Fix squashed layout on Route Options after period of time

### ISSUE THREAD

**Issue by mattbarker016** [cuappdev/ithaca-transit-ios#141]
Monica, you're probably the best person to fix this, but Yana, take a crack at it if you can!

![img_1853](https://user-images.githubusercontent.com/8039928/45598869-5c605580-b9b0-11e8-84d2-1970bd3658b9.PNG)

This bug occurs when a user search a route and does nothing for a period of time (about 5 minutes). This definitely happens when you leave the app and re-open it, and may also happen if you just leave it open.

The live route data changes from *on time* to *late* which causes part of the cell to appear squashed. This affects the height of the dot, and some of the y-coordinates.

**Comment by Omarrasheed** [comment]
Closing because I fixed this in snapkit PR
