### ISSUE TITLE
Move and adjust all client-facing strings into Constants.swift

### ISSUE THREAD

**Issue by myo3** [cuappdev/ithaca-transit-ios#145]
E.g. `Location Not Found` should be `Location not found`

This should be changed for all error states.

Some that I can think of:
- `Location Not Found` on search
- empty state on RouteOptionsVC

These strings should technically all be in our `Constants.swift` so should be  a relatively quick fix, but if it's not then make sure to move all client-facing strings to our `Constants.swift` file

**Comment by mattbarker016** [comment]
@myo3 Do you want to make this issue to be moving all client-facing strings into `Constants.swift`. Will definitely help with organization!

**Comment by myo3** [comment]
@mattbarker016 yeah i think that would be good. ill update the issue title & descript

**Comment by mattbarker016** [comment]
Where possible, modify Constants.swift Strings to have proper English capitalization. We just want them to be consistent!
