### ISSUE TITLE
Omit current location when updating map camera if not used in route

### ISSUE THREAD

**Issue by mattbarker016** [cuappdev/ithaca-transit-ios#166]
If a user searches a route not involving the current location, the map will still use the user's current location when updating the camera. When the current location is not within the route, don't use it to adjust the map. Look in `RouteDetail+ContentViewController.swift`.

**Example:** If you use the app while out of state, the app will first (correctly) fail and say you need to be closer. Then, if you update the "From Location" to a place within the county, valid routes will load, but the map will be panned to a corner of the county because it's trying to fit your current location and the route.

**Comment by Omarrasheed** [comment]
Closing because I fixed in #275
