### ISSUE TITLE
Flatten file hierarchy

### ISSUE THREAD

**Issue by mattbarker016** [cuappdev/ithaca-transit-ios#169]
Currently, in the `TCAT` folder, all of our `.swift` files are organized into folders mostly similar to the Xcode grouping. However, if we want to modify their location in Xcode, the file structure in the TCAT/ folder (within tcat-ios) would then be out of date and need to be changed. Based on talking with other developers and my own internships, most projects put all their `.swift` files into one folder, and organize them through Xcode only.

This is a 10 minute chore to re-hook up all the file sources, but I'll get this done once we chomp through PRs.

**Comment by myo3** [comment]
I disagree with that. I think Recast did that and it really made it hard to navigate all the files from an open-source perspective (i.e. on Github). So it'll make it hard for people on the team who don't necessary have the tcat repo running on their local computers (leads and members not on tcat) to see how all the files fit within the repo. Which sometimes you want to do if you're reviewing a PR or want to see how other pods do certain things.

**Comment by AAAstorga** [comment]
I disagree w/ @myo3. (sorry :P ) I think it is okay to do this style. The worst is when you want to move a file around and it breaks the links. I think it should be first the priority for our dev team, then the second is worrying about how it looks on GitHub. You can find examples of both styles all over GitHub, including ones from actual companies. I think it should be what makes sense for the dev team.

**Comment by mattbarker016** [comment]
Why is it harder to navigate the files? If people clone our repo and open it in Xcode, they'll see all the folders and can navigate easily. If not, you can use Command-F in the browser. I know code review tends to happen on GitHub.com, but it typically never involves file organization. When the `.xcodeproj` changes and we see the group it's in, we can keep track of organization.

**Comment by myo3** [comment]
alright alright seems consensus is for a flat file hierarchy. ill hold my peace :P

**Comment by mattbarker016** [comment]
@myo3 Actually, the file hierarchy was really useful for the Android team to better understand our codebase (like you mentioned), so I'm going to leave this as is!
