### ISSUE TITLE
Fix Directory Structure

### ISSUE THREAD

**Issue by say25** [cuappdev/ithaca-transit-ios#18]
Its kinda weird to have a repo with all the real files one level down.

**Comment by Jma353** [comment]
@say25 you don't even go here

**Comment by say25** [comment]
:(

**Comment by anniexcheng** [comment]
Wait Steven, don't change the file structure yet. Otherwise, Matt's going to have more trouble merging his stuff. I was planning on fixing file structure after he merged his stuff

**Comment by say25** [comment]
Yea I figured you guys should do it. I don't want to mess you up thats why I deleted my branch and just made an issue
