### ISSUE TITLE
Created routeSelected endpoint

### ISSUE THREAD

**Issue by mattbarker016** [cuappdev/ithaca-transit-ios#182]
We are going to log which routes users select on the client side. We will pass along the index of the route to backend. For now, this will be a single index, but once we start sorting routes into sections, it will include a `sectionIndex` and a `rowIndex`. This should be done on `didSelect`.

**Comment by mattbarker016** [comment]
aca4b8466358a0668a2b488b4f7aa4f2093a4492

**Comment by nateschickler0** [comment]
Changing the `sectionIndex` parameter to `section`, a String. Also adding a `routeId` String to the parameters to map to a specific route calculation.

**Comment by mattbarker016** [comment]
## New Spec

Every route will have a `routeId` key that is a unique identifier for the route. Per Nate's recommendation, this should be optional. 

This should be added to the Route.swift model once #184 is merged in.

**Comment by mattbarker016** [comment]
To be completed in #192.
