### ISSUE TITLE
Change Bus Stop Icon

### ISSUE THREAD

**Issue by Omarrasheed** [cuappdev/ithaca-transit-ios#200]
When we display search results, we have two different types of results: Bus stops and Google places locations. For Google places, they will stay as grey location icons but for Bus stops, instead of the current blue location icon, we want to switch them to a blue location icon with a bus in the middle (file can be found [here](https://www.figma.com/file/QyUBYdJeesuBiphl0I3uIz1j/iOS-Design-Kit?node-id=0%3A127)

**Comment by mattbarker016** [comment]
Note To Self: Need to refactor PlaceTableViewCell across app to just take in place and tweak in cell based on that as much as possible, with maybe some alterations outside.
