### ISSUE TITLE
Implement v2/route & UI

### ISSUE THREAD

**Issue by mattbarker016** [cuappdev/ithaca-transit-ios#203]
`/v2/route` is live now on dev server. It returns routes categorizing it based on `fromStop`, `boardingSoon` and `walking`. Check out ithaca-transit-backend [specs](https://github.com/cuappdev/ithaca-transit-backend#v2route--post). The main differences are moving from GET to POST and `arriveBy` has been renamed to `isArriveBy`.

**Comment by mattbarker016** [comment]
@kevinchan159 Did we move to the new v2 model outlined in this [issue](https://github.com/cuappdev/ithaca-transit-backend/issues/41)? We refactored out model to get rid of some extraneous parsing on client-side.

**Comment by kevinchan159** [comment]
the response is in the format
```
{
    "data" : {
       "fromStop" : [
             { "route1" : ... } , ...
        ],
        "boardingSoon" : [
             { "route2" : ... } , ...
        ],
        "walking" : [
             { "route3" : ... } , ...
        ],
    }
}
```
lmk if this isn't what you're asking about @mattbarker016

**Comment by mattbarker016** [comment]
I'm talking about the `Route` class. We came up with a new v2 model per the above issue, and I saw the `api/v2/route` syntax. Is the `v2` just because it's a breaking change, or does it include the new mode?

**Comment by kevinchan159** [comment]
we didn't change the `Route` model at all. its just that the response format of `/route` changed which is why its `/v2`. `/v1/route` returns an array of routes whereas `/v2/route` returns a dictionary with `fromStop`, `boardingSoon`, and `walking`

**Comment by mattbarker016** [comment]
Ok. What happened to that issue though, it doesn't look like it was ever continued?

**Comment by kevinchan159** [comment]
oh ok the issue was closed but it seems like it wasn't implemented. i reopened it and will work on it with @alanna-zhou this week

**Comment by mattbarker016** [comment]
I believe this was supposed to be put in place for Android to then implement. I think Jared Junyoung Lim worked on this, is there a branch anywhere?

**Comment by mattbarker016** [comment]
**TODO**

- [x] Fix UI and layout bugs presenting this data
- [x] Check edge cases

**Comment by mattbarker016** [comment]
#221
