### ISSUE TITLE
Max width iOS issue

### ISSUE THREAD

**Issue by mayafrai** [cuappdev/ithaca-transit-ios#211]
Routes with more than 10 stops are not visible on the bottom sheet when expanded. 

Investigate the max-width set for the bottom sheet.

Example: 
![IMG_0446](https://user-images.githubusercontent.com/25111415/54721327-112e2780-4b38-11e9-9048-53ffe58ef5c7.PNG)

@ywsang

**Comment by Omarrasheed** [comment]
Closing because fixed with #276
