### ISSUE TITLE
RouteDetail + DrawerVC visual on left side of cells not consistent

### ISSUE THREAD

**Issue by Omarrasheed** [cuappdev/ithaca-transit-ios#223]
**Steps to reproduce bug (Works sometimes):**

1. Find a route that has an expandable cell that would make the tableview expand past the bottom of the screen

2. Expand and collapse it

**Bug:**
<img src="https://user-images.githubusercontent.com/36868927/56381183-1f786d80-61e2-11e9-9d25-f86812993739.gif" width="300">

**Comment by Omarrasheed** [comment]
@lucyxubroad This may not still repro after doing the snapkit fixes but if u wanna look into it that'd be cool. Feel free to close it if no repro lol

**Comment by lucyxubroad** [comment]
@Omarrasheed I don't think this is an issue anymore? Let me know if this is not the case!

**Comment by lucyxubroad** [comment]
No longer reproducible!
