### ISSUE TITLE
Improve search results for chains with several locations

### ISSUE THREAD

**Issue by Omarrasheed** [cuappdev/ithaca-transit-ios#241]
Since we only display places by their names, we run into the issue where if a user searches a place/store that has several locations, the results with only show that same name repeated several times, although they are technically still different places. Should find a way to make it easier on the user to differentiate between the locations.

<img src="https://user-images.githubusercontent.com/36868927/57575283-8bcb4300-7415-11e9-907d-4949ac3cfad6.jpg" width="300">

**Comment by mattbarker016** [comment]
We used to always show the detail label for Google Places, or "Bus Stop" for bus stops. When did this change?
