### ISSUE TITLE
Remove the need for didSelectPlace in didSelectRowAt method of AllStopsViewController

### ISSUE THREAD

**Issue by Omarrasheed** [cuappdev/ithaca-transit-ios#283]
Seems like the way we're transitioning to the routeOptionsVC from AllStopsVC is by instantiating the VC and before it being presented, we call `didSelectPlace`. This is really wack because the searchBarView in the routeOptions isn't instantiated until the `viewDidLoad` function yet we call methods like `searchBarView.searchController?.dismiss(...)` within `didSelectPlace`. There is currently a fix to handle this case but we would like to move away from this function call, hopefully moving this logic of passing the selected Place into the instantiation of RouteOptionsVC.

### Reference:
 <img width="817" alt="Screen Shot 2019-09-01 at 2 42 21 PM" src="https://user-images.githubusercontent.com/36868927/64080863-b859e200-ccc6-11e9-93c7-b5df1c6e1769.png">

**Comment by lucyxubroad** [comment]
Resolved in #299
