### ISSUE TITLE
Flickering live tracking in routeOptionsCell

### ISSUE THREAD

**Issue by Omarrasheed** [cuappdev/ithaca-transit-ios#286]
Seems like the live tracking (specifically for the first route in the routeOptionsVC) tends to flicker on and off. Hopefully we can use this as an opportunity to refactor the way we handle live tracking updates for cells. We currently do a lot of weird stuff with times and the cells being the ones to manage their own timers, but if we move this to the VC handling the refetching of delays, we can potentially cut down on number of API calls and number of refreshes we make.

<img src="https://user-images.githubusercontent.com/36868927/64212730-4f19d080-ce78-11e9-9f13-5995ebc1e418.jpg" width="300">

**Comment by lucyxubroad** [comment]
Resolved in #317
