### ISSUE TITLE
Fix arrive by logic

### ISSUE THREAD

**Issue by usubzero** [cuappdev/ithaca-transit-ios#297]
Currently, selecting arrive by does not really show you routes that arrive by x time. 
<img width="451" alt="Screen Shot 2019-09-09 at 12 27 21 PM" src="https://user-images.githubusercontent.com/11025237/64548757-4d7b5d00-d2fd-11e9-9055-afea59583ec9.png">

**Comment by lucyxubroad** [comment]
Fixed!
