### ISSUE TITLE
Design Data Model

### ISSUE THREAD

**Issue by kevingreer** [cuappdev/ithaca-transit-ios#3]
Regardless of what the design ends up looking like, we will need models of stops, routes, etc. We should plan out what models we want, what fields/functions they have, and how they're related (at least roughly).

**Comment by mattbarker016** [comment]
Write up what we discussed from the note, and push the swift file into the master branch. Thanks!

**Comment by myo3** [comment]
@mattbarker016 I wasn't able to push to the master branch, but if you look under the data that 2 model files are there. I can also merge in my branch later, if you want, and then it'll be on master
