### ISSUE TITLE
Current Location Loading

### ISSUE THREAD

**Issue by AAAstorga** [cuappdev/ithaca-transit-ios#49]
Current Location table view cell takes some time to appear. I need to look in how to make it quicker.

**Comment by mattbarker016** [comment]
Have it always be present? Either load async in background, or start calculating upon pressing, using a UISpinner accessory

**Comment by AAAstorga** [comment]
I'm pretty sure locationManager does things async already

**Comment by mattbarker016** [comment]
So just present it always, and show a UISpinner if didLocationsUpdate hasn't fired yet

**Comment by AAAstorga** [comment]
I decided to go a different way using the OptionsViewController. No need for a UISpinner. Will push soon.
