### ISSUE TITLE
Continuing Map Routing Work

### ISSUE THREAD

**Issue by anniexcheng** [cuappdev/ithaca-transit-ios#7]
<img width="310" alt="screen shot 2017-02-15 at 5 52 37 pm" src="https://cloud.githubusercontent.com/assets/8130751/22999058/93c95998-f3a7-11e6-948d-b28b5e622e22.png">

**Comment by mattbarker016** [comment]
The designers made some minor UI changes to the route view, but not much has changed.
<img width="278" alt="latest map view" src="https://cloud.githubusercontent.com/assets/8039928/23238195/cfb4168c-f92e-11e6-8211-81ceeca8b020.png">
